### ISSUE TITLE
Question about implementation of audio log spectrogram 

### ISSUE THREAD

**Issue by zhang-jr** [ekazakos/temporal-binding-network#14]
Hello Evangelos,
Thanks for sharing your code!
I get a question here:
 In dataset.py, is there any different between your implementation of ‘_log_spectgram’ and the ‘librosa.feature.melspectrogram+librosa.amplitude_to_db’ ? 
I’m not familiar with this.

**Comment by ekazakos** [comment]
Hi,
Thanks for your interest in my code. Basically, I'm just extracting the log-spectrogram, while librosa.feature.melspectrogram takes it one step further and uses mel-filters to extract mel-frequencies from the spectrogram.

**Comment by zhang-jr** [comment]
ok, thanks for your quick response.

So,  for a fair comparison with librosa.feature.melspectrogram, I'm curious whether it affects the classification (audio) performance.

**Comment by ekazakos** [comment]
I've done this experiment in the past, it affects the performance a little bit but not much. I don't remember how much exactly the performance is affected, so you can try it yourself, but as I said don't expect a big difference.

**Comment by zhang-jr** [comment]
Thanks for your explanation! I really appreciate it.
