### ISSUE TITLE
About TBW width

### ISSUE THREAD

**Issue by TitaniumOne** [ekazakos/temporal-binding-network#15]
Thanks for your work!  I have some questions:
1. I dont know the means of the sentence in the paper 'In the TBN model instead, all modalities are trained simultaneously, and their combination is also learnt. 'Does it mean the variable b is learnable?
2. I have no idea of how to implement the TBW width part, which is a learnable variable according to the paper. Have you delt with this problem? @ekazakos

**Comment by ekazakos** [comment]
Hi, 

Thanks for your interest in our work! 

1. 'In the TBN model instead, all modalities are trained simultaneously': This means that each one of the streams (i.e. RGB, Flow, Audio backbones) are trained together as opposed to TSN where each one of the RGB and Flow streams are trained separately. 
'and their combination is also learnt': This means that we learn the fusion weights (fc layer on top of the concatenation) as opposed to TSN where fusion is performed as averaging the predictions of the single streams.

2. We do not claim that TBW width is learnable. From the paper: 'To avoid biasing the fusion towards longer or shorter action lengths, we calculate the window width b relative to the action video length. Our TBW is thus of variable width, where the width is a function of the length of the action. We note again that b can be set independently of the number of segments K, allowing the temporal windows to overlap.' 
This means that in our implementation we only set b=T where T is the length of an action, and we implement that in dataset.py in __getitem__(self, index) function. 
You could also use a predefined TBW width, independent of the length of the action, but this is not implemented in our code and you should implement it yourself. 

I hope this clarifies things. If you have any further questions, do let me know.

**Comment by TitaniumOne** [comment]
Thank you for your explanation and patience!
