### ISSUE TITLE
RGB+Flow doesn't work 

### ISSUE THREAD

**Issue by kamalesh0406** [ekazakos/temporal-binding-network#18]
When I try to run the code only for RGB and Flow modalities, the code throws an error due to line 207 in _train.py_ . The code requires that all the modalities be present in the argument if we want to run more than one. It would be preferable if you modified the code such that it considers scenarios in which only two modalities are available.

**Comment by ekazakos** [comment]
Lines 203-210 are not very important for training. You can delete them and the code will run without any issues, and without any important degradation in accuracy.
