### ISSUE TITLE
Epic Kitchen pretrained models

### ISSUE THREAD

**Issue by jomuecke** [ekazakos/temporal-binding-network#19]
Hello! Is it somehow possible to train on a different small dataset and use the Epic Kitchen Model for initalization ?

**Comment by ekazakos** [comment]
Hi!

To finetune on a different dataset, there are 2 steps needed:

1. Follow the instructions in **Train/evaluate with other datasets** to prepare your data in a format readable by this repo
2. After downloading the pretrained model (link provided in readme), use `args.pretrained` followed by the pretrained model's file in `train.py`.

If you have any difficulties particularly with step 1, please let me know.

**Comment by jomuecke** [comment]
Hi, thank you for your answer.

Training our Dataset without any pretrained Model or with the pretrained flow of Kinetics works perfectly fine. 
Our Dataset is pretty small with a small amount of Classes, but similar to the Epic Dataset so i'd like to use a pretrained model 

When trying to use one of the pretrained models in train.py i get:

```
Traceback (most recent call last):
  File "train.py", line 653, in <module>
    main()
  File "train.py", line 94, in main
    model.load_state_dict(state_dict_new)
  File "/home/local_admin/.conda/envs/tbn/lib/python3.6/site-packages/torch/nn/modules/module.py", line 777, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for TBN:
        size mismatch for fusion_classification_net.fc_verb.weight: copying a param with shape torch.Size([97, 512]) from checkpoint, the shape in current model is torch.Size([8, 512]).
        size mismatch for fusion_classification_net.fc_verb.bias: copying a param with shape torch.Size([97]) from checkpoint, the shape in current model is torch.Size([8]).
        size mismatch for fusion_classification_net.fc_noun.weight: copying a param with shape torch.Size([300, 512]) from checkpoint, the shape in current model is torch.Size([7, 512]).
        size mismatch for fusion_classification_net.fc_noun.bias: copying a param with shape torch.Size([300]) from checkpoint, the shape in current model is torch.Size([7]).
```

**Comment by ekazakos** [comment]
I just fixed the issue. I had forgotten to set `strict=False` in `load_state_dict()`. If you pull, you should be able to load the pretrained model now. Thanks for spotting this bug!

**Comment by jomuecke** [comment]
Somehow im still getting the same error 

```
=> loading pretrained TBN model from pretrained/TBN-epic-kitchens-100.pth
Traceback (most recent call last):
  File "train.py", line 653, in <module>
    main()
  File "train.py", line 94, in main
    model.load_state_dict(state_dict_new, strict=False)
  File "/home/local_admin/.conda/envs/tbn/lib/python3.6/site-packages/torch/nn/modules/module.py", line 777, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for TBN:
        size mismatch for fusion_classification_net.fc_verb.weight: copying a param with shape torch.Size([97, 512]) from checkpoint, the shape in current model is torch.Size([8, 512]).
        size mismatch for fusion_classification_net.fc_verb.bias: copying a param with shape torch.Size([97]) from checkpoint, the shape in current model is torch.Size([8]).
        size mismatch for fusion_classification_net.fc_noun.weight: copying a param with shape torch.Size([300, 512]) from checkpoint, the shape in current model is torch.Size([7, 512]).
        size mismatch for fusion_classification_net.fc_noun.bias: copying a param with shape torch.Size([300]) from checkpoint, the shape in current model is torch.Size([7]).
```

**Comment by ekazakos** [comment]
Pytorch docs for `load_state_dict()` ([link](https://pytorch.org/docs/stable/generated/torch.nn.Module.html#torch.nn.Module.load_state_dict)) mention that: "If `strict` is `True`, then the keys of `state_dict` must exactly match the keys returned by this module’s `state_dict()` function."

This means that a quick solution is to change the name of fc layers in `fusion_classification_net`, e.g. from `fc_verb` to `output_verb` and from `fc_noun` to `output_noun`. Then these fc layers will be ignored during initialisation from the pretrained model, because 1) we set `strict=False` and 2) the keys between your model and the pretrained model for the fc layers won't match.

Hopefully this solves your issue.

**Comment by jomuecke** [comment]
This solved it. 

Many thanks for your time
