### ISSUE TITLE
audio data &&  EPIC_train_action_labels.pkl and EPIC_test_val_action_labels.pkl

### ISSUE THREAD

**Issue by yztongzhan** [ekazakos/temporal-binding-network#3]
Hello， @ekazakos ！
Thank you for your code but I have some questions.

1.How  can I get the audio data ?

2.For EPIC_train_action_labels.pkl and EPIC_test_val_action_labels.pkl, how can I split the original EPIC_train_action_labels.pkl into them? Can you release yours?

Thanks!

**Comment by ekazakos** [comment]
Dear @yztongzhan ,
For the audio data I've just used ffmpeg to extract the audio stream from the video. I will upload guidelines on data preprocessing, and training and evaluations details later within the week. Thanks!

**Comment by yztongzhan** [comment]
@ekazakos ，EPIC_test_val_action_labels.pkl  will be released？

**Comment by ekazakos** [comment]
EPIC_train_action_labels.pkl and EPIC_val_action_labels.pkl have now been released.
