### ISSUE TITLE
Is any pretrained checkpoint available?

### ISSUE THREAD

**Issue by naykun** [ekazakos/temporal-binding-network#4]
Thanks for sharing! Would you please provide your checkpoints which have achieved the best performance and guidance on how to evaluate them？

**Comment by ekazakos** [comment]
I will release both guidelines for training and evaluating, as well as pretrained models later within the week. Thank you.

**Comment by ekazakos** [comment]
Hi, instructions for downloading pretrained weights have now been added in the README.

**Comment by naykun** [comment]
> Hi, instructions for downloading pretrained weights have now been added in the README.

Appreciate it.
