### ISSUE TITLE
train and val splits

### ISSUE THREAD

**Issue by swathikirans** [ekazakos/temporal-binding-network#5]
Thank you for the code and the pretrained models. I have two questions:
1) How are the train and validation splits generated?
2) I could not find the results of the proposed method on the given train/val split. It would be helpful if the results on this split are also reported so that a direct comparison with TBN can be done.

I would also like to know if you are planning to release the audio extracted from the video clips.

**Comment by ekazakos** [comment]
Hi @swathikirans,

1. In the readme, I explain how the train/val splits are generated. I can upload the python script as well if that helps.
2. I will upload the results on the val split soon.

I will not release the audio, as you can find detailed explanation on the readme on how to generate the audio, and the relevant scripts are provided as well.

**Comment by swathikirans** [comment]
Thank you for the reply

**Comment by swathikirans** [comment]
Hi @ekazakos,

Can I have an estimate regarding when the validation split results be made available?

**Comment by ekazakos** [comment]
Dear @swathikirans,

The validation results have been added to the readme. Im sorry for the delay, and thanks for your patience!

Best,

Vangelis
