### ISSUE TITLE
Extract the audio from the videos of EPIC

### ISSUE THREAD

**Issue by DianYe2333** [ekazakos/temporal-binding-network#7]
Hello,i have read your code for a few day.When i want to extract the audio data,i found the videos of EPIC is too large.So i have to prepare large free storage space for hard drive ,and spend a lot of time to download it.Can you give me the audio data you extracted? thanks a lot.

**Comment by ekazakos** [comment]
Hi,
Since the videos and the code to extract the audio are available, Im not planning to release the extracted audio. Thank you.

**Comment by i2isaalien** [comment]
> Hi,
> Since the videos and the code to extract the audio are available, Im not planning to release the extracted audio. Thank you.

**Comment by DianYe2333** [comment]
> Hi,
> Since the videos and the code to extract the audio are available, Im not planning to release the extracted audio. Thank you.

Thank you for the reply

**Comment by frostinassiky** [comment]
Hi @i2isaalien.
I extracted the audio and transformed the *.wav files into a dictionary pickle. I am not sure if I did everything correctly, but you can use the pickle file in my [google drive](https://drive.google.com/drive/folders/1z7Pvd-9j5Oar8ZJ3Ro6lOGdZum3E7kYw?usp=sharing).

**Comment by Kaiyue-Zhang** [comment]
> Hi @i2isaalien. I extracted the audio and transformed the *.wav files into a dictionary pickle. I am not sure if I did everything correctly, but you can use the pickle file in my [google drive](https://drive.google.com/drive/folders/1z7Pvd-9j5Oar8ZJ3Ro6lOGdZum3E7kYw?usp=sharing).

I want to know what your resampling rate is, because in the code it is 44000, but in the paper it is 24000.Thx
